// Design-sync barrel entry (consumed by .ds-sync/package-build.mjs via --entry).
// Re-exports the standalone Lyra DS primitives onto window.Lyra, and imports the
// i18n singleton so components using useTranslation() (e.g. StatusPill) render.
// Not part of the app build; safe to delete — regenerated by the sync.
import './src/i18n';

export { IconButton } from './src/components/IconButton';
export { MenuPicker } from './src/components/MenuPicker';
export { Avatar } from './src/components/Avatar';
export { Modal } from './src/components/Modal';
export { ConfirmDialog } from './src/components/ConfirmDialog';
export { Toggle } from './src/components/Toggle';
export { Checkbox } from './src/components/Checkbox';
export { Tooltip } from './src/components/Tooltip';
export { EmptyState } from './src/components/EmptyState';
export { StatusPill } from './src/components/StatusPill';
export { TagChip } from './src/components/TagChip';
export { ProviderIcon } from './src/components/ProviderIcon';
